-- -- Use Dictinct with Orderby to remove duplicate rows
-- SELECT DISTINCT ON (______) _____,
-- ______,
-- ______,
-- ______
 -- INTO retirement_titles
-- FROM _______
-- WHERE _______
-- ORDER BY _____, _____ DESC;


--- DELIVERABLE 1 ---

SELECT E.EMP_NO,
	E.FIRST_NAME,
	E.LAST_NAME,
	T.TITLE,
	T.FROM_DATE,
	T.TO_DATE INTO RETIREMENT_TITLES
FROM EMPLOYEES AS E
INNER JOIN TITLES AS T ON (E.EMP_NO = T.EMP_NO)
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31'
ORDER BY EMP_NO
SELECT EMP_NO,
	FIRST_NAME,
	LAST_NAME,
	TITLE
FROM RETIREMENT_TITLES



SELECT DISTINCT ON (EMP_NO) EMP_NO,
	FIRST_NAME,
	LAST_NAME,
	TITLE INTO UNIQUE_TITLES
FROM RETIREMENT_TITLES
WHERE TO_DATE = '9999-01-01'
ORDER BY EMP_NO,
	TO_DATE DESC;
    
SELECT COUNT(TITLE), title
INTO Retiring_Titles
FROM UNIQUE_TITLES
GROUP BY Title
ORDER BY COUNT(TITLE) DESC;




--- DELIVERABLE 2 ---

SELECT DISTINCT ON(E.EMP_NO) E.EMP_NO,
	E.FIRST_NAME,
	E.LAST_NAME,
	E.BIRTH_DATE,
	DE.FROM_DATE,
	DE.TO_DATE,
	T.TITLE 
INTO MENTORSHIP_ELIGIBILTY
FROM EMPLOYEES AS E
LEFT OUTER JOIN DEPT_EMP AS DE ON (E.EMP_NO = DE.EMP_NO)
LEFT OUTER JOIN TITLES AS T ON (E.EMP_NO = T.EMP_NO)
WHERE (E.BIRTH_DATE BETWEEN '1965-01-01' AND '1965-12-31')
ORDER BY E.EMP_NO;



















